### ISSUE TITLE
Collab tab won't stay hidden

### ISSUE THREAD

**Issue by dherault** [c9/c9.ide.collab#3]
Hi,

Just a regular c9 user here, reporting some _annoying_ bug :smile: 

When I open c9 the Collab tab is always shown: it does not behave like the others tabs that remember their visible/hidden state.
Is it a bug or a feature ?

I use chrome 44.

![image](https://cloud.githubusercontent.com/assets/4154003/9523716/a00b8542-4cdb-11e5-8bec-34b27b1bc130.png)

(What about "Loading your workspace, it will be just as you left it"? I left it with no collab tab ^^)

**Comment by nightwing** [comment]
This should be fixed by https://github.com/c9/c9.ide.collab/commit/fd08d9a12385408310306e3e8019a14c29f0e0e4, please comment if it still doesn't work
