### ISSUE TITLE
Open Active File doesn't open in collaborative mode

### ISSUE THREAD

**Issue by Emiel45** [c9/c9.ide.collab#4]
Clicking Open Active File on a collaborator will result in opening the file without being able to see the collaborator's cursor.

**Comment by nightwing** [comment]
Do you see this with sdk or c9.io? Soes opening from file tree work?

**Comment by Emiel45** [comment]
I'm experiencing this issue on c9.io instance with an ssh connected machine.
Closing the file and reopening it from the file menu fixes the problem.

**Comment by nightwing** [comment]
This was fixed in https://github.com/c9/c9.ide.collab/commit/10c224f9b88282bac35af78e62e52c614f24f1d3, please let us know if you still see any issues.
